
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1280x720")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    521.0,
    0.0,
    522.0,
    1024.0,
    fill="#000000",
    outline="")

canvas.create_text(
    227.0,
    547.0,
    anchor="nw",
    text="Segmentation Phase\n(Descending Aorta segmentation\nAscending Aorta segmentation\nSagittal segmentation)",
    fill="#000000",
    font=("Inter", 12 * -1)
)

canvas.create_rectangle(
    14.0,
    85.0,
    374.0,
    302.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    14.0,
    370.0,
    194.0,
    424.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    267.0,
    370.0,
    447.0,
    424.0,
    fill="#000000",
    outline="")

canvas.create_text(
    7.0,
    0.0,
    anchor="nw",
    text="GeoRecom",
    fill="#084A41",
    font=("Inter", 24 * -1)
)

canvas.create_rectangle(
    14.0,
    43.0,
    493.0,
    68.0,
    fill="#000000",
    outline="")

canvas.create_text(
    14.0,
    350.0,
    anchor="nw",
    text="Use your cursor to selcte the region on ",
    fill="#000000",
    font=("Inter", 16 * -1)
)

canvas.create_rectangle(
    1.0,
    528.0,
    524.0,
    528.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    323.0,
    346.0,
    403.0,
    373.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    14.0,
    436.0,
    474.0,
    461.0,
    fill="#000000",
    outline="")

canvas.create_text(
    27.0,
    535.0,
    anchor="nw",
    text="Note",
    fill="#000000",
    font=("Inter", 16 * -1)
)

canvas.create_rectangle(
    13.0,
    77.0,
    493.0,
    336.0029296875,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    527.0,
    122.0,
    947.0,
    359.56756591796875,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    659.0,
    290.0,
    1079.0,
    527.5675659179688,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    823.0,
    424.0,
    1243.0,
    661.1621704101562,
    fill="#000000",
    outline="")

canvas.create_text(
    527.0,
    23.0,
    anchor="nw",
    text="Select CT scan image ",
    fill="#000000",
    font=("Inter", 16 * -1)
)

canvas.create_rectangle(
    962.0,
    15.0,
    994.0,
    47.0,
    fill="#000000",
    outline="")

canvas.create_text(
    849.0,
    55.0,
    anchor="nw",
    text="XY/YZ/XZ/All of them",
    fill="#000000",
    font=("Inter", 16 * -1)
)
window.resizable(False, False)
window.mainloop()
